pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r index.html public/ # Ajusta segons els fitxers que vulguis copiar
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "developer"
      when: always